---

debug: true

server: "https://rke2.ord.pm8s.io:9345"

token: "{{ tmpl_rke2_token }}"

protect-kernel-defaults: true

tls-san:
  - "rke2.ord.pm8s.io"
  - "127.0.0.1"
  - "::1"

cluster-cidr: "{{ tmpl_cluster_cidr }}"
service-cidr: "{{ tmpl_service_cidr }}"
cluster-dns: "{{ tmpl_cluster_dns }}"

cni: none

disable-kube-proxy: true

disable:
  - rke2-ingress-nginx
