apiVersion: v1
kind: Secret
metadata:
  name: honkwatch-credentials
  namespace: monitoring
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:zVU+mvjv5KAXF4CGMRP6ifQq+lJ1Wsmvqfk20ppomCLU2A==,iv:ecg/ePS3RaN1HzmBqp2EjE4Sj6AL5h9dc8Z5OXPEcI0=,tag:iM3kPlSMK8sEXtnGts0iTA==,type:str]
  password: ENC[AES256_GCM,data:LSMS+GUDb8ywXYPMwK2PuXVkzlGO2fdmRJULr1AiDpuAwJ+ORn6oit+sYMh0VQB/pn9u/so2s3O/BhrjDDTJRA==,iv:sf/mktOonu9Ffu90+8ru7HZTFy3aItNAc97IKapjYUE=,tag:a5Z1rOPz4VN52V4bKJ5+Dw==,type:str]
sops:
  age:
    - recipient: age1yr9ws6dv3rck8wwtuwnqr3fmjnz59tcav5atdc727splmsyu6cfqk8uwf4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTXQ5TWpnYTJ5LzVSSjY4
        ZForQWszZzNQcnc4cnRRdUdlSis1ZTNPRGhVCmgvL2NUU0d6WVdBZ2RaZnl6VFk0
        eDZSN0ZpdUtmZG95eFZNNjNPZmZYMFEKLS0tIFk5SHNWZmU5K0NYdURiVkduZ1Mx
        QXhuTnU3am5KQi90RExEdEY4cFNqRzgKLedU+JxTNGiQYjyCWJt9PjtFsKo6XuEt
        OfTgKMX6TMSvskGSR816patJ1F4AD/XM2wrPkakORvrzsJKIKqEjNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T23:12:06Z"
  mac: ENC[AES256_GCM,data:k7/2nATa/hAOZcm+PDX6M7vW1nr8Baeo5HDav5pnKrwjbv7HT6sNKekFCwBp6zyNysaMdx7YkCI5KXo/v8eV4fgs/FZhU+yMcDiyww2iH0rsSWcatV3PTL7708Z0GT2WIgCwGKVx76FiVsxUNMdV+R6EaLBTayIj0vYGoGIIN2k=,iv:UP7tu1ykHowfx0w8oXUiXLEutd8oFi4gM35TQ0PGWk8=,tag:98ZzRHGyjya7EZzRR8LLhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
