---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: playm8s-operator
  namespace: flux-system
spec:
  interval: 60m
  url: https://helm.playm8s.io/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: playm8s-operator
  namespace: flux-system
spec:
  interval: 60m
  targetNamespace: playm8s-system
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: playm8s-operator
      sourceRef:
        kind: HelmRepository
        name: playm8s-operator
        namespace: flux-system
      interval: 60m
  values: {}
