apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cilium-bgp-peer-secret
  namespace: kube-system
stringData:
  password: ENC[AES256_GCM,data:yHFocvU4SDNVY5JKT+3V6A==,iv:u9m5+8/WXdIYAjWY7b4VGsTQwFTZ3mD5exTvUEH/s18=,tag:AZ+/ymPlNdFYd1McXcZS2Q==,type:str]
sops:
  age:
    - recipient: age1yr9ws6dv3rck8wwtuwnqr3fmjnz59tcav5atdc727splmsyu6cfqk8uwf4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Zm5HdHVKcHBwV2pjYmFw
        ZXZmUUpscVdnUm93SFJHcjhLajRkbE5OTUVjCkZWNW1BZXdLT3UxVnRoUW5QKzh4
        cDJ5Zm1WajV4WGdKU0p2WVFGc2pLQ2cKLS0tIEUzWHNCdUhQYUZpTTM0N3RXekpJ
        MXhMcjEzRjNFRDU3V3V0eDdwTlBWSlkKrKPxYx3QymfQbNqvkktWQY6D8z3UaqoD
        Yu9xytYv3Pp3KjNu7PIaVLD9XbDSOFqddg3kHhxGm6JjDWrXT38Q4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T23:12:06Z"
  mac: ENC[AES256_GCM,data:TtYBhSoi9ByYh94Wu+Qj8tN8isVbZUWZ78HQ4kf6hirXwtKSSRNOumErEJVy6X5KSPlywNfGDRG7L67f8LibA1+gElkT3gMbfdkoePDBcRF45m0UMem1sWYrNPoiZICISLuBWJfO+HOiu85rp7Lm2TrPm1FRgErNJeUAHbB0ews=,iv:95lxuVC2VpsnBJE4S1TnWGAt9Lf3fCEHEG8rxcCg4hk=,tag:Qz4cT4KJ0yFdNCoQgTJU6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
